--- 
rubyforge_project: darkfish-rdoc
project_requirements: {}

project_description: "A complete replacement for the default HTML generator for Rdoc, the\n\
  API documentation-extraction system for Ruby. "
rubyforge_group: deveiate
author_name: Michael Granger
project_homepage: http://deveiate.org/projects/Darkfish-Rdoc/
project_dependencies: 
  rdoc: ">= 2.1.0"
project_summary: A pretty (different) Rdoc HTML generator
project_name: Darkfish-Rdoc
version_file: rdoc/generator/darkfish.rb
additional_pkgfiles: 
- lib/rdoc/generator/**/*.{css,rhtml,png,js}
dev_dependencies: {}

author_email: ged@FaerieMUD.org
