--- 
excluded_pkgfiles: []

rubyforge_project: darkfish-rdoc
project_requirements: {}

project_pubdir: /usr/local/www/public/code
project_description: "A complete replacement for the default HTML generator for Rdoc, the\n\
  API documentation-extraction system for Ruby. "
rubyforge_group: deveiate
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/Darkfish-Rdoc/
project_dependencies: 
  rdoc: ">= 2.3"
project_summary: A pretty (different) Rdoc HTML generator
project_name: Darkfish-Rdoc
version_file: rdoc/generator/darkfish.rb
additional_pkgfiles: 
- lib/rdoc/generator/**/*.{css,rhtml,png,js}
dev_dependencies: {}

authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: To use the Darkfish formatter, just add '-f darkfish' to your rdoc command of choice.
